import type { Metadata } from "next";
import "./globals.css";
import HtmlLayout from "@/components/layouts/html-layout";
import RootProvider from "@/components/providers/root-provider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <HtmlLayout>
      <RootProvider>
        <Suspense>{children}</Suspense>
      </RootProvider>
    </HtmlLayout>
  );
}
